version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: retail_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql 
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - retail_network

  generator:
    build: ./generator
    container_name: retail_data_generator
    working_dir: /app
    volumes:
      - ./generator:/app:rw
      - ./data:/app/data:rw
    depends_on:
      db:
        condition: service_healthy
    networks:
      - retail_network
    command: /bin/bash -c "while true; do python3 -u generate_csv.py; sleep 50; done"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3001:3000"
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_DBNAME=metabase_db
      - MB_DB_PORT=3306
      - MB_DB_USER=${DB_USER}
      - MB_DB_PASS=${DB_PASSWORD}
      - MB_DB_HOST=db
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - retail_network

  
  adminer:
    image: adminer:latest
    container_name: retail_adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - retail_network
    depends_on:
      db:
        condition: service_healthy

  fix-permissions:
    image: alpine
    user: "0:0"
    volumes:
      - .:/opt/airflow
    command: >
      sh -c "chmod -R 777 /opt/airflow && chown -R 50000:0 /opt/airflow"

  postgres-airflow:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - retail_network

  airflow-webserver:
    build: .
    command: webserver
    depends_on:
      postgres-airflow:
        condition: service_healthy
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./great_expectations:/opt/airflow/great_expectations
      - ./etl_core:/opt/airflow/dags/etl_core
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW_UID=1000
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW_CONN_MYSQL_DWH=mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
      - TELEGRAM_BOT_CHAT_ID=${TELEGRAM_BOT_CHAT_ID}
      - TELEGRAM_BOT_API_KEY=${TELEGRAM_BOT_API_KEY}
      - AIRFLOW_CONN_TELEGRAM_CONN_ID=telegram://:${TELEGRAM_BOT_API_KEY}@default
    networks:
      - retail_network

  airflow-scheduler:
    build: .
    command: scheduler
    depends_on:
      postgres-airflow:
        condition: service_healthy
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./great_expectations:/opt/airflow/great_expectations
      - ./etl_core:/opt/airflow/dags/etl_core
    environment:
      - AIRFLOW_UID=1000
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW_CONN_MYSQL_DWH=mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
      - TELEGRAM_BOT_CHAT_ID=${TELEGRAM_BOT_CHAT_ID}
      - TELEGRAM_BOT_API_KEY=${TELEGRAM_BOT_API_KEY}
      - AIRFLOW_CONN_TELEGRAM_CONN_ID=telegram://:${TELEGRAM_BOT_API_KEY}@default
    networks:
      - retail_network

volumes:
  mysql_data:

networks:
  retail_network:
    driver: bridge
